name: Repo Backup Daily

on:
  schedule:
    - cron: "00 19 * * *"  # 12:30AM IST
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create backup archive
        run: |
          mkdir backup
          zip -r backup/coretexela_backup_${{ github.run_id }}.zip .

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-backup-${{ github.run_id }}
          path: backup/
